[TASK] Implement new router
ffrgb/meshviewer pull request #123
Opened 2017-04-16 18:43 UTC by xf-

## Description

Add new router #83 

## Motivation and Context

Provide links of current view and allows to link locations, mode, link, node and languages. Also be extendable for future features like filters or maybe skin (dark/light)

# Testlinks
https://forum.freifunk.net/t/meshviewer-development/14701/10

## Checklist:

- [x] My code follows the code style of this project. (CI will test it anyway and also needs approval)
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2017-04-18 21:02 UTC, genofire requested changes

2017-04-18 21:02 UTC, genofire commented on lib/infobox/link.js
> +    a2.href =  router.generate({ node: d.target.node_id });
heißt es nicht `generateLink`?

2017-04-18 21:02 UTC, genofire commented on lib/gui.js
> +          router.fullUrl({ view: 'graph', lat: undefined });
sollte das leeren der Position nicht im Router durchgeführt werden.

2017-04-18 21:02 UTC, genofire commented on lib/utils/language.js
>        localStorage.setItem('language', getLocale(event.target.value));
vielleicht sollte `setSelectLocale` die Funktion `setLocale` aufrufen

2017-04-18 21:21 UTC, xf- commented on lib/gui.js
> +          router.fullUrl({ view: 'graph', lat: undefined });
graph hat keine Position und lat ist der Parameter im router der ausfuehrt

2017-04-18 21:43 UTC, xf- commented on lib/utils/language.js
>        localStorage.setItem('language', getLocale(event.target.value));
is nur der event listener und das navigieren passiert sowieso und triggered alles, da URL Änderungen von Hand ja auch gehen sollen

2017-04-19 08:08 UTC, genofire commented on lib/gui.js
> +          router.fullUrl({ view: 'graph', lat: undefined });
sollte es hierfür nicht ein `if (data.view === 'graph') { data.lat = undefined;}` in fullUrl des routers geben?

2017-04-19 08:30 UTC, genofire commented on lib/gui.js
> +          router.fullUrl({ view: 'graph', lat: undefined });
Hab einfach angst, das gelegtntlich das `lat` vergessen wird.

2017-04-19 08:34 UTC, xf- commented on lib/gui.js
> +          router.fullUrl({ view: 'graph', lat: undefined });
Ist tendenziell nicht schlimm, die sidebar ändert sich.

2017-04-20 14:05 UTC, xf- commented on lib/gui.js
> +          router.fullUrl({ view: 'graph', lat: undefined });
Der Code hat sich ja inzwischen geändert, setzte aber weiterhin alle auf undefined, die im anderen view nur wenig bringen und eher verwirren. Das die Felder mitgezogen werden ist wie beschrieben deep  Argument notwendig, sonst wird es maximal full mit den Standardargumenten

2017-04-20 19:54 UTC, merged