[TASK] Use snabbdom for DOM
ffrgb/meshviewer pull request #125
Opened 2017-04-23 16:32 UTC by xf-

## Description

Replaces virtual-dom

## Motivation and Context

Virtual-dom is unmaintained and slower. I compared different library and this was fest solution with patch functionality

## How Has This Been Tested?

Browserstack

## Screenshots/links (if appropriate):

## Checklist:

- [x] My code follows the code style of this project. (CI will test it anyway and also needs approval)

2017-04-24 11:39 UTC, genofire requested changes

2017-04-24 11:39 UTC, genofire commented on app.js
>      'virtual-dom': '../node_modules/virtual-dom/dist/virtual-dom',
delete `virtual-dom` ...

2017-04-24 11:39 UTC, genofire commented on lib/proportions.js
> -      var fwTable = statusTable.cloneNode(false);
:+1:

2017-04-24 11:39 UTC, genofire commented on lib/sorttable.js
>      var el = document.createElement('table');
has el existis at his own? (could it not be always self.el)?

2017-04-25 18:34 UTC, xf- commented on lib/sorttable.js
>      var el = document.createElement('table');
yes, patch needs a element to patch. i can try to use null

2017-04-25 19:26 UTC, genofire commented on lib/sorttable.js
>      var el = document.createElement('table');
i mean, you could use: `self.el = document.createElement('table')`

2017-04-25 19:27 UTC, genofire commented on lib/sorttable.js
> +      el = V.patch(el, elNew);
and merge this file with it

2017-04-25 21:51 UTC, merged