[TASK] Show firmware version in info box
ffrgb/meshviewer pull request #151
Opened 2017-09-05 19:36 UTC by mwarning

The firmware should be shown in the info box.

2017-09-05 21:18 UTC, xf- commented
Should be already returned by showFirmware.
https://github.com/ffrgb/meshviewer/pull/151/files#diff-1b7411720abb55d6bdfa6f6f09761b2cR37

2017-09-05 21:21 UTC, mwarning commented
ah, it is not displayed for us because we do not have 'base'.

2017-09-05 21:25 UTC, xf- commented
Yeah that should be changed

2017-09-05 21:38 UTC, mwarning commented
@xf- fixed.

2017-09-05 21:44 UTC, xf- requested changes

2017-09-05 21:44 UTC, xf- commented on lib/infobox/node.js
> +      if (release === null) {
should work in both cases.

```javascript
    function showFirmware(d) {
      return [
        helper.dictGet(d.nodeinfo, ['software', 'firmware', 'release']),
        helper.dictGet(d.nodeinfo, ['software', 'firmware', 'base'])
      ].filter(function (n) {
        return n !== null;
      }).join(' / ') || undefined;
    }
```

2017-09-06 16:16 UTC, mwarning commented on lib/infobox/node.js
> +      if (release === null) {
@xf- sure, go ahead. :-)

2017-09-06 21:36 UTC, mwarning commented
thanks

2017-09-06 21:37 UTC, xf- commented
no problem - this should work in every case

2017-09-06 21:43 UTC, xf- approved these changes

2017-09-06 21:44 UTC, merged