[BUGFIX] fix uptime in nodelist
ffrgb/meshviewer pull request #172
Opened 2017-10-26 14:02 UTC by genofire

2017-10-26 20:03 UTC, xf- requested changes

2017-10-26 20:03 UTC, xf- commented on lib/nodelist.js
> +        return Math.round(s) + 'm';
Maybe add space like distance and other lists

2017-10-26 20:03 UTC, xf- commented on lib/nodelist.js
> +    var s = (now - uptime) / (60 * 1000);
if uptime is undefined it will throw an error and you test for undefined in line 9

2017-10-26 20:03 UTC, xf- commented on lib/nodelist.js
> +        n._uptime = new Date(e.uptime).getTime();
why _? looks like a private variable

2017-10-26 20:03 UTC, xf- commented on lib/nodelist.js
> +      return Math.round(s) + 'y';
Do we need year in nodelist for uptime? nearly 3 years without firmware update or reboot

2017-10-26 20:03 UTC, xf- commented on lib/nodelist.js
> +  var now = new Date().getTime();
var now; is enough or? only setData can fill the table and needs now.

2017-10-26 20:03 UTC, xf- commented on lib/nodelist.js
> +    var s = (now - uptime) / (60 * 1000);
Calc each loop (2k nodes = 2000 times 60*1000 every minute) - also increases complexity.

2017-10-27 08:40 UTC, xf- approved these changes

2017-10-27 09:04 UTC, closed without merging

2017-10-27 09:04 UTC, genofire commented
Manno mit den ordentlichen squashed geht es wohl nicht

2017-10-27 09:05 UTC, xf- commented
future branch kannst force push machen :)

2017-10-27 09:07 UTC, genofire commented
hab ich ja jetzt bei mir -> wollte im PR die einzelnen commit noch haben, aber im branch ja nur ein gesquashed PR-commit (brauch ja nicht jeder upstream meine netten commit sehen)

2017-10-27 10:21 UTC, genofire commented
Hab den fallback zu `lastseen` wieder eingebaut, wenn der Knote offline ist (`is_online`):
https://github.com/ffrgb/meshviewer/commit/4a9e8397342df5ef001ef55f88b1a06d27f09fe5#diff-7d27cceca12c06020a4cd8794bc8b5c0R11

2017-10-27 10:58 UTC, genofire commented
https://github.com/ffrgb/ffrgb/commit/8e20cc36dc078eb9350325549a6ca54112bf3eb8#diff-7d27cceca12c06020a4cd8794bc8b5c0R94

Nun aber -> sry