[BUGFIX] forcegraph show only online nodes
ffrgb/meshviewer pull request #180
Opened 2017-10-27 23:47 UTC by genofire

The nodelist of nodes in graph did not came from graph.json any more.

2017-10-28 14:58 UTC, xf- requested changes
Has an issue with unknown targets with our test meshviewer.json

2017-10-28 15:41 UTC, xf- commented
What do you think about:

```local.diff
diff --git a/lib/forcegraph.js b/lib/forcegraph.js
index b661bde..1ba6351 100644
--- a/lib/forcegraph.js
+++ b/lib/forcegraph.js
@@ -198,28 +198,20 @@ define(['d3-selection', 'd3-force', 'd3-zoom', 'd3-drag', 'd3-timer', 'd3-ease',
 
       self.setData = function setData(data) {
         intNodes = data.nodes.all.filter(helper.online).map(function (d) {
-          var e;
-          if (d.node_id in dictNodes) {
-            e = dictNodes[d.node_id];
-          } else {
-            e = {};
-            dictNodes[d.node_id] = e;
-          }
-
-          e.o = d;
+          var e = { o: d };
+          dictNodes[d.node_id] = e;
 
           return e;
         });
 
         intLinks = data.links.map(function (d) {
-          var e = {};
-          e.o = d;
-          e.source = dictNodes[d.source.node_id];
-          e.target = dictNodes[d.target.node_id];
-          e.color = linkScale(d.source_tq);
-          e.color_to = linkScale(d.target_tq);
-
-          return e;
+          return {
+            o: d,
+            source: dictNodes[d.source.node_id],
+            target: dictNodes[d.target.node_id],
+            color: linkScale(d.source_tq),
+            color_to: linkScale(d.target_tq)
+          };
         });
 
         force.nodes(intNodes);
```

2017-10-29 00:57 UTC, genofire commented
Die erste map function ist so complex, da inzwischen in ggf. `e.x` und `e.y` existieren und damit durch `setData` die nodes und ihre position im forcegraph nicht neu berechnet werden müssen.

2017-10-29 10:21 UTC, xf- approved these changes

2017-10-29 10:21 UTC, merged