[BUGFIX] calc loadavg on nproc > 1
ffrgb/meshviewer pull request #245
Opened 2018-02-03 10:42 UTC by genofire

## Checklist:

- [x] My code follows the code style of this project. (CI will test it anyway and also needs approval)

2018-02-03 10:49 UTC, genofire commented
No idea, which node has nproc > 1 on https://deploy-preview-245--meshviewer.netlify.com/#/en/map

2018-02-04 10:03 UTC, genofire commented on lib/utils/node.js
> +    return showBar(d.loadavg.toFixed(2), d.loadavg / d.nproc || 1, d.loadavg >= d.nproc);
`|| 1` creates a "100 %" bar if loadavg is `0`

2018-02-04 13:33 UTC, xf- requested changes

2018-02-04 13:33 UTC, xf- commented on lib/utils/node.js
> +    return showBar(d.loadavg.toFixed(2), d.loadavg / d.nproc || 0, d.loadavg >= d.nproc);
idea was (d.nproc || 1). Provide at least one core to avoid dividing by 0

2018-02-11 11:41 UTC, xf- approved these changes

2018-02-11 11:42 UTC, merged