[DOC] Update Readme
ffrgb/meshviewer pull request #49
Opened 2017-02-06 23:28 UTC by xf-

2017-02-06 23:52 UTC, genofire requested changes

2017-02-06 23:52 UTC, genofire commented on README.md
> +- Translation support - https://crowdin.com/project/meshviewer - Contact us for new languages
wo kontaktieren?

2017-02-06 23:53 UTC, xf- commented on README.md
> +- Translation support - https://crowdin.com/project/meshviewer - Contact us for new languages
We use github and we have a support section in Readme.

2017-02-07 00:19 UTC, genofire commented on README.md
> +- Translation support - https://crowdin.com/project/meshviewer - Contact us for new languages
Create a Issue for new languages?

2017-02-07 00:20 UTC, xf- commented on README.md
> +- Translation support - https://crowdin.com/project/meshviewer - Contact us for new languages
for exmaple or ask in irc

2017-02-07 00:30 UTC, genofire commented on README.md
> +- Translation support - https://crowdin.com/project/meshviewer - Contact us for new languages
- Create a issue for new languages?

2017-02-07 00:30 UTC, genofire approved these changes

2017-02-07 00:55 UTC, merged