[DOC] Update README
ffrgb/meshviewer pull request #65
Opened 2017-02-12 18:04 UTC by xf-

## Description

Please review and add comments to improve the README..

## Motivation and Context

Out-of-date, format could be improved.

2017-02-14 11:06 UTC, genofire commented on README.md
> +https://regensburg.freifunk.net/meshviewer/ standalone
https://map.bremen.freifunk.net/ (with a patch for a different `nodes.json` generated by [https://github.com/FreifunkBremen/respond-collector](respond-collector )

2017-02-14 11:10 UTC, genofire approved these changes

2017-02-17 10:17 UTC, SimJoSt requested changes
I supplied some suggestions for general improvements.

2017-02-17 10:17 UTC, SimJoSt commented on README.md
> +_Some features are maybe implemented/merged_
suggestion:
> _Some similar features might have been implemented/merged_

2017-02-17 10:17 UTC, SimJoSt commented on README.md
> +https://map.bremen.freifunk.net/ (with a [patch](https://github.com/FreifunkBremen/meshviewer-ffrgb/pull/1) for a different `nodes.json` generated by [respond-collector](https://github.com/FreifunkBr
missing trailing `)`

2017-02-17 10:17 UTC, SimJoSt commented on README.md
> +  - Currently avialable en, de & fr
I would insert a `:` after `available`

2017-02-17 10:17 UTC, SimJoSt commented on README.md
> +#### Main differences to https://github.com/ffnord/meshviewer<br>
trailing `<br>` not necessary

2017-02-17 10:17 UTC, SimJoSt commented on README.md
> +#### Main differences to https://github.com/ffnord/meshviewer<br>
As it is not possible to see, that where this repo was forked from, I would expand the description with:
> (fork origin; not maintained anymore)

Either at the end of the title or as a new line.
Maybe merge it with the current description:
>_fork origin; not maintained anymore; not actively watched, some similar features might have been implemented/merged_

2017-02-17 10:17 UTC, SimJoSt commented on README.md
>  - Icon font with only needed icons
suggestion to improve English:
> Icon font with needed icons only

2017-02-17 10:17 UTC, SimJoSt commented on README.md
>  - Upgrade to grunt v1.x (Tested with Node.js 4 LTS,6 LTS,7 Linux,OSX,W**)
change `grunt` to uppercase:
> Upgrade to Grunt v1.x (Tested with Node.js 4 LTS,6 LTS,7 Linux,OSX,W**)

2017-02-17 10:17 UTC, SimJoSt commented on README.md
>  - Upgrade to grunt v1.x (Tested with Node.js 4 LTS,6 LTS,7 Linux,OSX,W**)
suggestion to improve English
> Moved some css and js inline

2017-02-17 10:17 UTC, SimJoSt commented on README.md
> +  - Currently avialable en, de & fr
correct typo: `avialable` -> `available`

2017-02-17 10:17 UTC, SimJoSt commented on README.md
>  - Upgrade to grunt v1.x (Tested with Node.js 4 LTS,6 LTS,7 Linux,OSX,W**)
move `css` and `js` to uppercase:
> Inline some CSS and JS

2017-02-17 10:17 UTC, SimJoSt commented on README.md
>  - Rewrite Scss, SASS lint and variables for easy customization/adjustments
to the best of my knowledge I would change `Scss` to `SCSS` and `SASS` to `Sass`

2017-02-17 10:17 UTC, SimJoSt commented on README.md
>    - Load only  moment.js without languages - Languages included in translations
missing `are`:
> Languages are included in translations

2017-02-17 10:17 UTC, SimJoSt commented on README.md
>  - Rbush v2 - performance boost in last versions. (Positions labels and clients on the map)
I would change `Rbush` to `RBush` and remove the `.`

2017-02-17 10:17 UTC, SimJoSt commented on README.md
>  - [A lot more in commit history](https://github.com/ffrgb/meshviewer/commits/develop)
add `the` to improve English:
> [A lot more in the commit history](https://github.com/ffrgb/meshviewer/commits/develop)

2017-02-17 10:17 UTC, SimJoSt commented on README.md
> +_npm is still possible, but yarn is much faster https://yarnpkg.com/_
add `to use` to improve English:
> _npm is still possible to use, but yarn is much faster https://yarnpkg.com/_

2017-02-17 10:17 UTC, SimJoSt commented on README.md
>  - Feel free to open an issue for a problem or a idea.
change `a idea` to `an idea` to improve English:
> Feel free to open an issue for a problem or an idea.

2017-02-17 10:17 UTC, SimJoSt commented on README.md
>  - Feel free to open an issue for a problem or a idea.
add a link to `issue`:

    Feel free to open an [issue](https://github.com/ffrgb/meshviewer/issues/new) for a problem or an idea.

2017-02-17 10:17 UTC, SimJoSt commented on README.md
> +- IRC: irc.hackint.org #freifunkRGB or development-channel #meshviewer
maybe a little more structure for the IRC channels and IRC links:

    - IRC on irc.hackint.org
        - [#freifunkRGB](irc://irc.hackint.org/freifunkRGB)
        - [#meshviewer](irc://irc.hackint.org/meshviewer) (development-channel)

2017-02-17 10:17 UTC, SimJoSt commented on README.md
> +These tools need a lot of infrastructure and prodice a free account for open source software.
`prodice` to `provide` to improve English

2017-02-17 10:17 UTC, SimJoSt commented on README.md
>  - [BrowserStack](https://www.browserstack.com/) for providing a awesome testing service for hundreds of browsers
change `a awesome` to `an awesome` to improve English

2017-02-17 10:17 UTC, SimJoSt commented on README.md
>  - [Crowdin](https://crowdin.com/) for providing easy non-developer translation environment
change `providing easy` to `providing an easy` to improve English

2017-02-17 10:19 UTC, SimJoSt commented
At the moment the changed features are announced in a number of different ways:
- add
- adds
- added

If there is any interest in using just one style throughout the whole list, I will make some suggestions.

2017-02-17 21:45 UTC, xf- commented on README.md
>  - Rewrite Scss, SASS lint and variables for easy customization/adjustments
i changed everything to lowercase

2017-02-18 08:56 UTC, SimJoSt commented on README.md
>  - Rewrite Scss, SASS lint and variables for easy customization/adjustments
^^

2017-02-18 16:57 UTC, closed without merging