[WIP] init d3 v4
ffrgb/meshviewer pull request #75
Opened 2017-02-22 17:19 UTC by genofire

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots/links (if appropriate):

## Checklist:

- [ ] My code follows the code style of this project. (CI will test it anyway and also needs approval)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2017-02-24 12:11 UTC, genofire commented
comment for myself :)
build a own d3 main required definition ...
```
var d3 = Object.assign({}, require("d3-format"), require("d3-geo"), require("d3-geo-projection"));
```

2017-03-05 17:23 UTC, xf- requested changes

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph/draw.js
> +  const nonUplinkColor = '#F2E3C6';
lowercase hex - maybe we find a way to move all hardcoded canvas stuff into a setting js.

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph/draw.js
> +  const clientColor = 'rgba(230, 50, 75, 1.0)';
opacity 1 - please use hex

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph/draw.js
> +  const cableColor = '#50B0F0';
Maybe we should think about colors or styles (line style ...)

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph/draw.js
> +      ctx.fillStyle = '#fff';
duplicate - set in line 26 - colors should be const or config

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph/draw.js
> +    if (d.o.type === 'fastd' || d.o.type === 'L2TP') {
We use this condition multiple times - maybe create a helper

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph/math.js
> +    if (t > 1) {
else if (will not be validated if first if matches)

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph/draw.js
> +'use strict';
all over use strict inside define (can't remember why)

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph.js
> +define(['d3-selection', 'd3-force', 'd3-zoom', 'd3-drag', 'forcegraph/math', 'forcegraph/draw'], function (d3Selection, d3Force, d3Zoom, d3Drag, math, draw) {
2 kines, avoid scrollbars

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph.js
> +    var el;
If we use `const`, we should consider `let`
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/let

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph.js
> +      canvas.style.width = el.offsetWidth + 'px';
style is unnecessary - 100vw 100vh if we need it. (height, width attribute is necessary)

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph.js
>        canvas.style.width = el.offsetWidth + 'px';
not needed, could be done via CSS

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph.js
> +        .filter(function (d) {
Remove unnecessary code

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph.js
> +       if (d.o.type === 'fastd' || d.o.type === 'L2TP') {
Should be moved to helpers or similar or do we have a field Boolean vpn?

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph.js
> +         .scaleExtent([ZOOM_MIN, ZOOM_MAX])
to many indents

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph.js
> +      .alphaTarget(0.1);
const, avoid hardcoded settings in middle of code

2017-03-05 17:23 UTC, xf- commented on lib/forcegraph.js
> +      .subject(function () {
indents

2017-03-05 17:41 UTC, xf- commented on lib/forcegraph/draw.js
> +    ctx.moveTo(d.x + 3, d.y);
wie findest?

```javascript
    ctx.moveTo(d.x + 3, d.y);
    ctx.arc(d.x, d.y, 6, 0, 2 * Math.PI);
    ctx.fillStyle = nonUplinkColor;
    ctx.globalAlpha = 1;
    ctx.fill();
```

2017-03-05 18:37 UTC, genofire commented on lib/forcegraph.js
> +        .filter(function (d) {
Should we allow to select vpn links? It is not in the develop branch.

2017-03-05 18:38 UTC, genofire commented on lib/forcegraph/draw.js
> +  const cableColor = '#50B0F0';
Jep, also for https://github.com/ffrgb/meshviewer/blob/develop/lib/map/clientlayer.js#L46 -> later

2017-03-05 18:41 UTC, genofire commented on lib/forcegraph.js
> +       if (d.o.type === 'fastd' || d.o.type === 'L2TP') {
boolean :+1:

2017-03-05 18:45 UTC, genofire commented on lib/forcegraph.js
> +      .subject(function () {
hier nicht korrekt?

2017-03-05 19:01 UTC, genofire commented on lib/forcegraph/draw.js
> +    ctx.moveTo(d.x + 3, d.y);
done

2017-03-05 19:06 UTC, genofire commented on lib/forcegraph.js
> +    var el;
back to `var` is it okay?

2017-03-05 22:58 UTC, xf- commented on lib/forcegraph.js
> +    var el;
i prefer let and const, but if we rewrite complete file, we should be consistent.

2017-03-05 22:58 UTC, xf- commented on lib/forcegraph.js
> +        .filter(function (d) {
why not - vpn has also quality

2017-03-05 22:59 UTC, xf- commented on lib/forcegraph.js
> +      .subject(function () {
allgemein passt das nicht, glaube function is nur ein space, paar doppelte leerzeilen

2017-03-06 18:53 UTC, xf- commented on lib/forcegraph/math.js
> +  let self = this;
let won't work :( - requirejs with uglify trhows an error

2017-03-06 23:33 UTC, xf- commented on lib/forcegraph/draw.js
> +    if (d.source.x < -width && d.target.x < -width || d.source.y < -height && d.target.y < -height ||
das muesste bei jedem drag ausgefuehrt werden, sonst is ein teil der nodes eventuell nie sichtbar. weis nicht ob das soviel bringt.

2017-03-07 08:06 UTC, genofire commented on lib/forcegraph/draw.js
> +    if (d.source.x < -width && d.target.x < -width || d.source.y < -height && d.target.y < -height ||
Wird es, durch den `.tick` im `forcegraph.js`.
Doch ich hab nicht auf transform (z.B. Zoom) geachtet.

2017-03-07 09:11 UTC, genofire commented on lib/forcegraph/draw.js
> +    if (d.source.x < -width && d.target.x < -width || d.source.y < -height && d.target.y < -height ||
Ähnlich gab es dies auch bereits vorher mit ein filter und der `function visibleNodes(d) {` - doch wenn jeweils erst ein filter und dann ein foreach kommt, ist dies nicht wirklich performant

2017-03-08 12:09 UTC, genofire commented on lib/forcegraph/draw.js
> +    if (d.o.type === 'fastd' || d.o.type === 'L2TP') {
Will make a PR (Issue) for other components, too.
I am for a boolean variable.

2017-03-08 18:11 UTC, xf- commented on lib/forcegraph/draw.js
> +  self.setHighlight = function setHighlight(newValue) {
Add a empty line between functions

2017-03-09 23:44 UTC, xf- commented
merged via 98f175d

2017-03-09 23:44 UTC, closed without merging